import { VocabularyItem } from "./types";

export const schoolVocabulary: VocabularyItem[] = [
  {
    id: "1",
    korean: "학부모",
    romanization: "hakbumo",
    english: "Parents",
    description: "Parents or guardians of students",
    example: "학부모님께 알려드립니다",
    exampleTranslation: "Notice to parents",
  },
  {
    id: "2",
    korean: "현장학습",
    romanization: "hyeonjang hakseup",
    english: "Field Trip",
    description: "Educational trip outside of school",
    example: "박물관 현장학습이 있습니다",
    exampleTranslation: "There is a field trip to the museum",
  },
  {
    id: "3",
    korean: "동의서",
    romanization: "dong-uiseo",
    english: "Permission Form",
    description: "Consent or permission document",
    example: "동의서를 제출해 주세요",
    exampleTranslation: "Please submit the permission form",
  },
  {
    id: "4",
    korean: "급식",
    romanization: "geupshik",
    english: "School Lunch",
    description: "Meals provided at school",
    example: "오늘의 급식 메뉴",
    exampleTranslation: "Today's lunch menu",
  },
  {
    id: "5",
    korean: "가정통신문",
    romanization: "gajeong tongsinmun",
    english: "School Newsletter",
    description: "Letter sent home to parents",
    example: "이번 주 가정통신문입니다",
    exampleTranslation: "This week's school newsletter",
  },
  {
    id: "6",
    korean: "학급",
    romanization: "hakgeup",
    english: "Class/Classroom",
    description: "Student's class or homeroom",
    example: "3학년 2반 학급",
    exampleTranslation: "Grade 3, Class 2",
  },
  {
    id: "7",
    korean: "담임선생님",
    romanization: "damim seonsaengnim",
    english: "Homeroom Teacher",
    description: "Main teacher responsible for a class",
    example: "담임선생님과 상담",
    exampleTranslation: "Consultation with homeroom teacher",
  },
  {
    id: "8",
    korean: "숙제",
    romanization: "sukje",
    english: "Homework",
    description: "Assignments to complete at home",
    example: "오늘의 숙제를 확인하세요",
    exampleTranslation: "Please check today's homework",
  },
  {
    id: "9",
    korean: "시험",
    romanization: "siheom",
    english: "Exam/Test",
    description: "Academic assessment or test",
    example: "중간시험 일정",
    exampleTranslation: "Midterm exam schedule",
  },
  {
    id: "10",
    korean: "방과후",
    romanization: "banggwahu",
    english: "After School",
    description: "After-school programs or activities",
    example: "방과후 수업 신청",
    exampleTranslation: "After-school class registration",
  },
  {
    id: "11",
    korean: "학부모 상담",
    romanization: "hakbumo sangdam",
    english: "Parent-Teacher Conference",
    description: "Meeting between parents and teachers",
    example: "학부모 상담 주간",
    exampleTranslation: "Parent-teacher conference week",
  },
  {
    id: "12",
    korean: "준비물",
    romanization: "junbimul",
    english: "Things to Prepare",
    description: "Items students need to bring",
    example: "내일 준비물: 도시락, 물통",
    exampleTranslation: "Tomorrow's items: lunch box, water bottle",
  },
];